version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    container_name: jekyll-site
    command: jekyll serve --watch --force_polling --incremental --host 0.0.0.0
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"

  # rake-clean:
  #   image: jekyll/jekyll:3.8
  #   container_name: jekyll-rake-clean
  #   command: rake clean
  #   volumes:
  #     - .:/srv/jekyll

  # rake-check:
  #   image: jekyll/jekyll:3.8
  #   container_name: jekyll-rake-check
  #   command: rake check
  #   volumes:
  #     - .:/srv/jekyll